// <auto-generated />
namespace Work.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class convertstatustype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(convertstatustype));
        
        string IMigrationMetadata.Id
        {
            get { return "202208150848279_convert-status-type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
