// <auto-generated />
namespace Work.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mergetosandsecurity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mergetosandsecurity));
        
        string IMigrationMetadata.Id
        {
            get { return "202208160632346_merge-tos-and-security"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
